### ISSUE TITLE
Pop miner cli crashes because of invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Leonardiae** [hemilabs/heminetwork#266]
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

The PoP miner CLI crashed because of this error. This happened for a second time. First time happened when running 0.4.0. After upgrading to 0.4.3 it happened again. Before installing 0.4.0 this did not happen before.

```
2024-09-27 14:35:12 INFO popm popm.go:358 Mining an L2 keystone at height 1611125...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x744f48]

goroutine 32708 [running]:
github.com/coder/websocket.(*Conn).writer(...)
        github.com/coder/websocket@v1.8.12/write.go:97
github.com/coder/websocket.(*Conn).write(0x0, {0xabbd80, 0xc000f51ab0}, 0xc000130000?, {0xc0003f6d80, 0x4c, 0x480})
        github.com/coder/websocket@v1.8.12/write.go:105 +0x68
github.com/coder/websocket.(*Conn).Write(0x879fc0?, {0xabbd80?, 0xc000f51ab0?}, 0x9312c0?, {0xc0003f6d80?, 0x879fc0?, 0xc000132500?})
        github.com/coder/websocket@v1.8.12/write.go:45 +0x25
github.com/coder/websocket/wsjson.write.func1({0xc0003f6d80?, 0x4c, 0xc000f979c0?})
        github.com/coder/websocket@v1.8.12/wsjson/wsjson.go:58 +0x45
github.com/coder/websocket/internal/util.WriterFunc.Write(0x0?, {0xc0003f6d80?, 0xc000132500?, 0x20?})
        github.com/coder/websocket@v1.8.12/internal/util/util.go:7 +0x24
encoding/json.(*Encoder).Encode(0xc000f97ae0, {0x879fc0, 0xc000132500})
        encoding/json/stream.go:231 +0x1ee
github.com/coder/websocket/wsjson.write({0xabbd80, 0xc000f51ab0}, 0x0, {0x879fc0, 0xc000132500})
        github.com/coder/websocket@v1.8.12/wsjson/wsjson.go:63 +0x145
github.com/coder/websocket/wsjson.Write(...)
        github.com/coder/websocket@v1.8.12/wsjson/wsjson.go:49
github.com/hemilabs/heminetwork/api/protocol.(*Conn).WriteJSON(0xc000c07c70, {0xabbd80, 0xc000f51ab0}, {0x879fc0, 0xc000132500})
        github.com/hemilabs/heminetwork/api/protocol/protocol.go:550 +0xe6
github.com/hemilabs/heminetwork/api/protocol.Write({0xabbd80, 0xc000f51ab0}, {0xab9890, 0xc000c07c70}, {0xab7c40?, 0xdeeaa0?}, {0xc0003a4812, 0x2}, {0x879a40, 0xdeeaa0})
        github.com/hemilabs/heminetwork/api/protocol/protocol.go:189 +0x21b
github.com/hemilabs/heminetwork/api/protocol.(*Conn).Write(...)
        github.com/hemilabs/heminetwork/api/protocol/protocol.go:650
github.com/hemilabs/heminetwork/api/protocol.(*Conn).Call(0xc000c07c70, {0xabbd80, 0xc000f51ab0}, {0xab7c40, 0xdeeaa0}, {0x879a40, 0xdeeaa0})
        github.com/hemilabs/heminetwork/api/protocol/protocol.go:594 +0x29f
github.com/hemilabs/heminetwork/api/bfgapi.Call({0xabbd80?, 0xc000f51ab0?}, 0x1?, {0x879a40?, 0xdeeaa0?})
        github.com/hemilabs/heminetwork/api/bfgapi/bfgapi.go:247 +0x4a
github.com/hemilabs/heminetwork/service/popm.(*Miner).handleBFGCallCompletion(0xc0000b60e0, {0xabbd10, 0xc000c2ab90}, 0xc000c07c70, {{0x879a40?, 0xdeeaa0?}, 0xc000f765b0?})
        github.com/hemilabs/heminetwork/service/popm/popm.go:753 +0x1de
created by github.com/hemilabs/heminetwork/service/popm.(*Miner).handleBFGWebsocketCall in goroutine 32405
        github.com/hemilabs/heminetwork/service/popm/popm.go:827 +0x10c

```

### Expected behaviour

.

### Environment

Version: 
Operating System: 
Architecture:

**Comment by Leonardiae** [comment]
Does not happen anymore (since mainnet).
